### ISSUE TITLE
Favicon doesn't update for AWS China

### ISSUE THREAD

**Issue by onelaview** [JB4GDI/awsfaviconupdater#10]
The extension doesn't work on AWS China.

AWS China is a different entity (https://www.amazonaws.cn/en/) that offer a subset of similar services available in AWS Global. The domain in URL is a bit different, for example in S3,

**AWS Global:** `https://s3.console.aws.amazon.com/s3/home`
**AWS China:** `https://console.amazonaws.cn/s3/home`

or in EC2,

**AWS Global:** `https://<region>.console.aws.amazon.com/ec2/v2/home`
**AWS China:** `https://console.amazonaws.cn/ec2/v2/home`

Here is a captured screenshot showing favicon not updated on AWS China:
https://ibb.co/J3ZZXHB

If would be great if this extension also be able to update favicon on AWS China website.
Thanks!

**Comment by JB4GDI** [comment]
Hey onelaview,

I keep going back and forth on this - the last time I added a domain (the USA Govcloud), it basically forced people to redownload the extension and it was a bad user experience.  But also, if something in the URL changes at amazonaws.cn, the two websites can go separate ways which may make things complicated.

I felt like the best thing to do was to make an exact copy of the current extension, but it only works on amazonaws.cn.  I submitted it, and it lives here: https://chrome.google.com/webstore/detail/aws-favicon-update-china/gnaakldfabdlcfcicadbibdcbaohefao

Let me know if that works!
