### ISSUE TITLE
More EC2 Icons

### ISSUE THREAD

**Issue by cfarrend** [JB4GDI/awsfaviconupdater#11]
Hey, really like the extension :)

One thing I have noticed is that EC2 has a lot of services attached to it that are services in their own right. Would be cool if we could get icons for services like EIP, ELB, ASG, etc. Could make it optional

Looking at the code it might need a bit of extra checks in it and may make it more complex but just throwing the idea out there. Can have a look into it

e.g
**Auto Scaling Group**
![rsz_console_autoscaling_icon88db8ba69cc884b5be96decb9e80b0f9dff17e50](https://user-images.githubusercontent.com/12799795/61608097-db8b7d80-ac94-11e9-8267-b6aefc1de3ac.png)

**Elastic IP**
![rsz_compute__networking_copy_amazon_ec2_elastic_ip-512](https://user-images.githubusercontent.com/12799795/61608287-75ebc100-ac95-11e9-8d6d-b4e1b490c585.png)

**Elastic Load Balancer**
![rsz_elb-icon](https://user-images.githubusercontent.com/12799795/61608327-9ddb2480-ac95-11e9-8f20-816eca720bed.png)

**Comment by JB4GDI** [comment]
This was an amazing idea!  And oh man did that take a long time.  I had to track down all of the icons and resize/rework them, but it's done and they look incredible!

Thanks for the suggestion and I'm glad you've been enjoying using it!
