### ISSUE TITLE
[Improvement] - Allow default icon for docs

### ISSUE THREAD

**Issue by slaughtr** [JB4GDI/awsfaviconupdater#9]
Hi there! Great extension, I love it, recommended it to coworkers. 

It would be great if there was a way to turn off favicon changes for docs.aws.amazon.com, as I keep getting them mixed up with console tabs. It's not a major thing and I can definitely see where others might prefer the way it is, but it would definitely help me.

Alternatively if there was a way to add a color mask of some kind to the favicon for docs pages that would differentiate, that would probably be great, too!

Thanks!

**Comment by JB4GDI** [comment]
That's a great catch and I am so sorry about that!  I should be able to pull that without too much trouble once I have some free time this week - and I think setting it to the standard 'docs' favicon for all those might be the least confusing solution all-around.

**Comment by JB4GDI** [comment]
That took way too long but the change works and it's being uploaded.  Thanks for catching this!
